name: autopr
on: push
jobs:
  pr_test:
    name: testing PR
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: [0]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install cryptography
      - name: New Branch
        run: |
          git checkout -b update_latest/${{ matrix.alpha }}
          git push --set-upstream origin update_latest/${{ matrix.alpha }}
      - name: Insert Key
        run: |
          echo ${{ secrets.FILEKEY }} >> filekey.key
      - name: Run update script
        run: python update_latest_all.py ${{ matrix.alpha }} 10000
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest
          git diff-index --quiet HEAD || git commit -m 'update: package latest json'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_latest/${{ matrix.alpha }}
      - name: Create Pull Request
        id: pr_id
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Pulling update_latest/${{ matrix.alpha }} into main"
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_latest/${{ matrix.alpha }}
          base: develop
          delete-branch: true
          labels: "automerge"
      - name: Enable Pull Request Automerge
        if: steps.pr_id.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          pull-request-number: ${{ steps.pr_id.outputs.pull-request-number }}
          merge-method: squash