name: ETL
on: 
  schedule:
    - cron: "0 12 * * *"
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  update_package_names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install beautifulsoup4==4.12.0
          pip install requests==2.28.2
      - name: Run update script
        run : |
         python update_package_names.py
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data
          git diff-index --quiet HEAD || git commit -m 'update: package names'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_latest_json:
    name: Upload Latest Json for Each Package
    needs: update_package_names
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install cryptography
      - name: New Branch
        run: |
          git checkout -b update_latest/${{ matrix.alpha }}
      - name: Insert Key
        run: |
          echo ${{ secrets.FILEKEY }} >> filekey.key
      - name: Run update script
        run: python update_latest_all.py ${{ matrix.alpha }} 10
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest
          git diff-index --quiet HEAD || git commit -m 'update: package latest json'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_latest/${{ matrix.alpha }}
      - uses: repo-sync/pull-request@v2
        name: Pull Request
        with:
          source_branch: update_latest/${{ matrix.alpha }}
          destination_branch: main
          pr_title: "Pulling update_latest/${{ matrix.alpha }} into main"
          pr_body: "[bot] An automated PR"
          pr_reviewer: "jeffrey82221"
          pr_draft: true
          pr_label: "automerge"
          github_token: ${{ secrets.PERSONAL_TOKEN }}
  automerge:
    name: Merge and Close the PRs
    runs-on: ubuntu-latest
    needs: update_latest_json
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          merge-method: squash
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          review: ${{ github.event.inputs.review }}
          dry-run: false
  merge_n_push_latest:
    name: Merge Updated Branches of all Latest Package
    needs: automerge
    if: always()
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branches: ['0 1 2 3 4 5 6 7 8 9']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Git Pull Main
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main
          git checkout main
      - name: Git Merge
        run: | 
          for VARIABLE in ${{ matrix.branches }}
          do
              git pull --squash origin update_latest/$VARIABLE || echo 'update_latest/$VARIABLE does not exists'
              git add data/latest || echo 'git add nothing $VARIABLE'
              git commit -m 'update: latest json of package in $VARIABLE' || echo 'git add nothing $VARIABLE'
          done
        shell: bash
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
      - name: Git Delete
        if: always()
        run: |
          for VARIABLE in ${{ matrix.branches }}
          do
              git push origin -d update_latest/$VARIABLE || echo 'git delete nothing'
          done
  update_release_time:
    name: Do Release Time Table ETL
    needs: merge_n_push_latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install tqdm
          pip install pandas==1.4.2
          pip install cryptography
          pip install pyarrow==8.0.0
      - name: Insert Key
        run: |
          echo ${{ secrets.FILEKEY }} >> filekey.key
      - name: RUN ETL
        run: |
          python update_release_time.py
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/release_time
          git diff-index --quiet HEAD || git commit -m 'update: release time table'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main     
