name: Image Experiment
on: push
jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t my-image:${{ github.sha }} .
          docker save -o my-image.tar my-image:${{ github.sha }}
      - name: Upload image to cache
        uses: actions/upload-artifact@v2
        with:
          name: my-image-cache
          path: my-image.tar
  use_image:
    name: Try using image
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - name: Download image cache
        uses: actions/download-artifact@v2
        with:
          name: my-image-cache
      - name: Load image
        run: docker load -i my-image.tar
      - name: Run Docker container
        run: |
          # Run Docker container with the loaded image
          docker run --rm my-image:${{ github.sha }} bash \
            debug.sh