name: Update Latest Json
on: 
  schedule:
    - cron: "0 12 * * *"
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main
jobs:
  update_package_names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install beautifulsoup4==4.12.0
          pip install requests==2.28.2
      - name: Run update script
        run : |
         python update_package_names.py
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data
          git diff-index --quiet HEAD || git commit -m 'update: package names'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_latest_json:
    name: Upload Latest Json for Each Package
    needs: update_package_names
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install cryptography
      - name: New Branch
        run: |
          git checkout -b update_latest/${{ matrix.alpha }}
      - name: Insert Key
        run: |
          echo ${{ secrets.FILEKEY }} >> filekey.key
      - name: Run update script
        run: python update_latest_all.py ${{ matrix.alpha }} 10
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest
          git diff-index --quiet HEAD || git commit -m 'update: package latest json'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_latest/${{ matrix.alpha }}
  merge_n_push_latest:
    name: Merge Updated Branches of all Latest Package
    needs: update_latest_json
    if: always()
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branches: ['0 1 2 3 4 5 6 7 8 9']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Git Pull Main
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main
          git checkout main
      - name: Git Merge
        run: | 
          for VARIABLE in ${{ matrix.branches }}
          do
              git pull --squash origin update_latest/$VARIABLE || echo 'update_latest/$VARIABLE does not exists'
              git add data/latest || echo 'git add nothing $VARIABLE'
              git commit -m 'update: latest json of package in $VARIABLE' || echo 'git add nothing $VARIABLE'
          done
        shell: bash
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
      - name: Git Delete
        if: always()
        run: |
          for VARIABLE in ${{ matrix.branches }}
          do
              git push origin -d update_latest/$VARIABLE || echo 'git delete nothing'
          done
  check_schema:
    name: Checking the Schema of Latest Json(s)
    needs: update_latest_json
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install JSkiner
          pip install black
          pip install tqdm
          pip install blosc
          pip install scalable-cuckoo-filter
          pip install cryptography
      - name: Insert Key
        run: |
          echo ${{ secrets.FILEKEY }} >> filekey.key
      - name: Sample and Decrypt Json
        run: |
          python sample_n_decrypt.py data/latest ./decrypt 10000
      - name: Run JSkiner 
        run: jskiner --in-path ./decrypt --nworkers 2 --verbose true --out data/latest.schema --batch-size 1000 --cuckoo-path data/latest.cuckoo --cuckoo-size 50000000 --cuckoo-fpr 0.1
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest.schema
          git add data/latest.cuckoo
          git diff-index --quiet HEAD || git commit -m 'update: package latest schema'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
          
